import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLocalization {
  static String _locale = 'en';
  static final ValueNotifier<bool> isArabicNotifier = ValueNotifier<bool>(false);

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _locale = prefs.getString('language') ?? 'en';
    isArabicNotifier.value = (_locale == 'ar');
  }

  // Alias for init used in main.dart
  static Future<void> loadSavedLanguage() => init();

  static String get currentLocale => _locale;

  static Future<void> setLocale(String locale) async {
    _locale = locale;
    isArabicNotifier.value = (locale == 'ar');
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', locale);
  }

  static Future<void> toggleLanguage() async {
    final newLocale = (_locale == 'en') ? 'ar' : 'en';
    await setLocale(newLocale);
  }

  static String get(String key) {
    if (_locale == 'ar') {
      return _ar[key] ?? _en[key] ?? key;
    }
    return _en[key] ?? key;
  }

  static final Map<String, String> _en = {
    'login_title': 'ControlEx',
    'login_subtitle': 'Sign in to continue',
    'email': 'Email',
    'password': 'Password',
    'forgot_password': 'Forgot Password?',
    'login_btn': 'Login',
    'google_btn': 'Sign in with Google',
    'no_account': 'Don\'t have an account? Sign up',
    'dashboard': 'Dashboard',
    'create_widgets': 'Create Widgets',
    'account': 'Account',
    'no_widgets': 'No widgets, add some now!',
    'account_preferences': 'Account & Preferences',
    'personal_info': 'Personal Information',
    'username': 'Username',
    'new_password_optional': 'New Password (optional)',
    'update_profile': 'Update Profile',
    'app_preferences': 'App Preferences',
    'language': 'Language / اللغة',
    'english_ar': 'English / عربي',
    'email_notifications': 'Email Notifications',
    'email_desc': 'Receive important updates in your inbox',
    'security_alerts': 'Security Alerts',
    'security_desc': 'Notify on new login attempts',
    'security_settings': 'Security Settings',
    'two_factor_auth': 'Two-Factor Authentication (2FA)',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'active_sessions': 'Active Sessions',
    'data_management': 'Data Management',
    'export_config': 'Export Account Data',
    'import_config': 'Import Config',
    'clear_data': 'Clear All Data',
    'delete_account': 'Delete Account Permanently',
    'logout': 'Logout',
    'terminal': 'Terminal',
    'terminal_hint': 'Enter command...',
    'send': 'Send',
    'status_connected': 'Connected',
    'status_disconnected': 'Disconnected',
    'layout_saved': 'Layout Saved!',
    'toggle_failed': 'Toggle Failed',
    'google_sign_in_msg': 'Google sign in requires Firebase setup.',
    'login_failed': 'Login Failed',
    'network_error': 'Network error, please try again later',
    'login_required': 'Login required',
    'banned_title': 'Account Banned',
    'banned_msg': 'Your account has been restricted by the administration. Please contact support to resolve this issue.',
    'contact_admin': 'Support & Inquiries',
    'whatsapp_contact': 'Contact via WhatsApp',
    'email_contact': 'Contact via Email',
    'close': 'Close',
    'admin_panel': 'Admin Panel',
    'admin_desc': 'Manage users and system logs',
    'technical_support': 'Technical Support',
    'local_control': 'Local Control',
    'local_desc': 'Control devices over local network',
    'save_api_keys': 'Save API Keys',
    'update_failed': 'Update Failed',
    'profile_updated': 'Profile Updated successfully!',
    'api_keys_saved': 'API Keys saved successfully!',
    'data_cleared': 'Data cleared successfully',
    'no_ip_selected': 'No IP Selected',
    'add_ip_hint': 'Press Settings to add IP and widgets',
    'add_widget': 'Add Widget',
    'error_sending_value': 'Error sending value',
    'server_waking_up': 'Server is waking up...',
    'free_hosting_hint': 'Free hosting needs time to start 😅',
    'server_error_retry': 'Could not connect to server. Pull to refresh.',
    'retry': 'Retry',
    'notifications': 'Notifications',
    'no_notifications': 'No notifications yet',
    'wait_sec': 'Wait %s seconds',
    'users': 'Users',
    'logs': 'Logs',
    'quota': 'Quota',
    'banned_users': 'Banned',
    'no_users': 'No users found',
    'active': 'Active',
    'suspended': 'Suspended',
    'super_admin': 'Super Admin',
    'widgets': 'Widgets',
    'suspend': 'Suspend',
    'activate': 'Activate',
    'sessions': 'Sessions',
    'user': 'User',
    'admin': 'Admin',
    'system_logs': 'System Logs',
    'client_errors': 'Client Errors',
    'no_logs': 'No logs found',
    'broadcast_notif': 'Broadcast Notification',
    'broadcast_desc': 'Send an instant notification to all or a specific user',
    'target': 'Target',
    'all_users': 'All Users',
    'notif_title_hint': 'Notification Title',
    'notif_body_hint': 'Notification Body...',
    'send_notif': 'Send Notification',
    'adafruit_quota': 'Adafruit IO Quota',
    'remaining': 'Remaining',
    'no_banned_devices': 'No banned devices',
    'unknown_device': 'Unknown Device',
    'at_date': 'At date',
    'unban': 'Unban',
    'notif_sent': 'Notification sent successfully!',
    'error_loading_data': 'Error loading data',
    'no_quota_data': 'No quota data available',
    'system_errors': 'System Errors',
    'create_widget': 'CREATE WIDGET',
    'edit_widget': 'EDIT WIDGET',
    'widget_details': 'Widget Details',
    'widget_name': 'Widget Name',
    'feed_name': 'Data Path / Feed Name',
    'firebase_db_url': 'Firebase Database URL',
    'firebase_secret': 'Firebase Database Secret',
    'provider': 'Data Provider',
    'provider_adafruit': 'Adafruit IO',
    'provider_firebase': 'Firebase RTDB',
    'widget_type': 'Widget Type',
    'commands': 'Commands',
    'on_command': 'ON Command',
    'off_command': 'OFF Command',
    'configuration': 'Configuration',
    'unit_hint': 'Unit (e.g. °C, %)',
    'min_value': 'Minimum Value',
    'max_value': 'Maximum Value',
    'primary_color': 'Primary Color',
    'existing_widgets': 'EXISTING WIDGETS',
    'no_widgets_yet': 'No widgets built yet.',
    'widget_created': 'Widget Created!',
    'widget_updated': 'Widget Updated!',
    'widget_deleted': 'Widget Deleted!',
    'device_ip': 'Device IP Address',
    'ip_address': 'IP Address (e.g. 192.168.1.100)',
    'save': 'Save',
    'checking_connection': 'Checking connection...',
    'device_connected': 'Device Connected ✓',
    'device_disconnected': 'Device Disconnected',
    'command_path': 'Command Path',
    'ip_saved': 'IP Address saved: ',
    // Onboarding Tour translations
    'tour_welcome_title': 'Welcome to ControlEx! 🚀',
    'tour_welcome_desc': 'Let\'s take a quick 1-minute tour to explore the app features and show you how to control your devices!',
    'tour_drawer_title': 'Main Navigation Drawer ☰',
    'tour_drawer_desc': 'Access your Account, Create Widgets settings, App localization, and Admin panels easily from here.',
    'tour_grid_title': 'Interactive Dashboard 📱',
    'tour_grid_desc': 'This is your smart control center! You can view sensor data, press buttons, adjust sliders, use joysticks, or type terminal commands here.',
    'tour_notifications_title': 'System Alerts & Notifications 🔔',
    'tour_notifications_desc': 'View live alarms, sensor threshold alerts, and cloud push notifications to stay updated instantly.',
    'tour_edit_title': 'Custom Layout Designer 🎨',
    'tour_edit_desc': 'Click here to enter Edit Mode. You can drag and drop to rearrange widgets and resize them to design your perfect dashboard!',
    'tour_mic_title': 'AI Voice Control 🎙️',
    'tour_mic_desc': 'Speak to your home! Press the mic button and say commands like "turn on light" or "open gate" to control devices via voice.',
    'tour_add_title': 'Create Custom Widgets ➕',
    'tour_add_desc': 'Click here to build new control widgets connected to your Adafruit IO feeds or local network devices in seconds!',
    'tour_end_title': 'You\'re all set! 🎉',
    'tour_end_desc': 'You have mastered ControlEx! Start building your smart IoT dashboard now and enjoy full control.',
    'tour_next': 'Next',
    'tour_back': 'Back',
    'tour_skip': 'Skip',
    'tour_finish': 'Finish',
    'tour_start': 'Start Tour',
    'tour_interact_hint': 'Please tap the highlighted area to continue.',
    'tour_tap_to_continue': 'Tap to continue',
    // Multi-page additions
    'tour_settings_transition_title': 'Widget Settings ⚙️',
    'tour_settings_transition_desc': 'Let\'s click Next to enter the Widget Settings and see how to configure custom feeds!',
    'tour_settings_name_title': 'Widget Name',
    'tour_settings_name_desc': 'Enter a clear name for your widget (e.g. Living Room Light). Type it, then tap Next.',
    'tour_settings_feed_title': 'Data Feed',
    'tour_settings_feed_desc': 'Enter the feed name or select one from your provider. This links the widget to your device.',
    'tour_settings_type_title': 'Widget Type',
    'tour_settings_type_desc': 'Select the type of control. Is it a toggle switch, a slider, or a sensor? Choose one then tap Next.',
    'tour_settings_save_title': 'Save and Create 💾',
    'tour_settings_save_desc': 'Once ready, click this button to add the widget to your main dashboard. Let\'s see the offline Local Control dashboard next!',
    'tour_local_grid_title': 'Offline Local Control 📶',
    'tour_local_grid_desc': 'This dashboard allows you to control your ESP/smart devices directly over your local WiFi network, fast and completely offline! Next, let\'s look at account preferences.',
    'tour_account_lang_title': 'App Preferences ⚙️',
    'tour_account_lang_desc': 'Toggle the language instantly between Arabic and English, or switch to offline Local Control setup from here.',
    'tour_account_support_title': 'Technical Support 📞',
    'tour_account_support_desc': 'Need help? Launch direct contact with developers via Email or WhatsApp in one tap!',
    // Sandbox Guided Practice
    'sandbox_title': 'Interactive Sandbox 🎯',
    'sandbox_step1': 'Welcome to the Sandbox! Tap the + button to create your first dummy widget.',
    'sandbox_step2': 'Awesome! Enter a name for your widget and tap Save.',
    'sandbox_step3': 'Great, the widget is here! Now tap the Edit button ✏️ at the top to arrange it.',
    'sandbox_step4': 'Now you can drag the widget to move it, or pull its corner to resize it. Try it out!',
    'sandbox_success': 'Outstanding! 🎉 You have completed the training and are ready to use the app.',
    'sandbox_finish_btn': 'Start Now',
    // Automations Screen
    'automations': 'Automations',
    'automations_subtitle': 'Create smart IF/THEN rules',
    'create_rule': 'Create Rule',
    'edit_rule': 'Edit Rule',
    'if_trigger': 'IF',
    'then_action': 'THEN',
    'select_sensor': 'Select Sensor',
    'select_widget': 'Select Widget',
    'select_condition': 'Select Condition',
    'enter_value': 'Enter Value',
    'greater_than': 'Greater than (>)',
    'less_than': 'Less than (<)',
    'equal_to': 'Equal to (=)',
    'not_equal': 'Not equal (≠)',
    'action_turn_on': 'Turn ON Widget',
    'action_turn_off': 'Turn OFF Widget',
    'action_send_notif': 'Send Push Notification',
    'action_send_email': 'Send Email Alert',
    'action_send_feed': 'Send Value to Feed',
    'select_action': 'Select Action',
    'rule_name': 'Rule Name',
    'rule_name_hint': 'e.g. Night Light Auto',
    'scenario_running': 'Running',
    'scenario_stopped': 'Stopped',
    'no_rules': 'No automation rules yet',
    'no_rules_hint': 'Tap + to create your first smart rule!',
    'rule_created': 'Rule Created!',
    'rule_updated': 'Rule Updated!',
    'rule_deleted': 'Rule Deleted!',
    'delete_rule_confirm': 'Delete this rule?',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'save_rule': 'Save Rule',
    'notif_message': 'Notification Message',
    'notif_message_hint': 'e.g. Temperature is too high!',
    'email_address': 'Email Address',
    'feed_value': 'Value to Send',
    'my_scenarios': 'My Scenarios',
    // Power Saving
    'power_saving': 'Power Saving',
    'power_saving_desc': 'Reduce server load by polling less frequently',
    'power_saving_on': 'Power Saving ON — polling every ~60s',
    'power_saving_off': 'Power Saving OFF — polling every ~10s',
    'power_saving_enabled': 'Power Saving Enabled ⚡',
    'power_saving_disabled': 'Power Saving Disabled',
    // Admin Automations
    'admin_automations': 'Automations & Power Saving',
    'admin_automations_subtitle': 'Monitor user automations and manage power saving per user.',
    'admin_automations_subtitle_ar': 'مراقبة أتمتة المستخدمين وإدارة توفير الطاقة لكل مستخدم.',
    'total_automations': 'Total Automations',
    'active_automations': 'Active',
    'inactive_automations': 'Inactive',
    'no_automations': 'No automations',
    'power_saving_mode': 'Power Saving',
    // Power saving reminder
    'power_saving_reminder_title': 'Power Saving Mode ⚡',
    'power_saving_reminder_msg': 'If you don\'t need real-time updates, please enable Power Saving mode to keep the system stable and reduce server load.',
    'enable_now': 'Enable Now',
    'later': 'Later',
    // Smart Scenes / Macros
    'smart_scenes': 'Smart Scenes',
    'smart_scenes_subtitle': 'Execute multiple commands at once',
    'quick_scenes': 'Quick Scenes',
    'create_scene': 'Create Scene',
    'edit_scene': 'Edit Scene',
    'delete_scene': 'Delete Scene',
    'scene_name': 'Scene Name',
    'scene_name_hint': 'e.g. Cinema Mode, Sleep Mode',
    'scene_icon': 'Scene Icon',
    'scene_color': 'Theme Color',
    'show_on_dashboard': 'Show on Dashboard',
    'no_scenes': 'No smart scenes yet',
    'no_scenes_hint': 'Tap + to build your first smart scene!',
    'scene_created': 'Smart Scene Created!',
    'scene_updated': 'Smart Scene Updated!',
    'scene_deleted': 'Smart Scene Deleted!',
    'select_devices': 'Select Devices & Commands',
    'select_devices_desc': 'Choose widgets and the commands to send when this scene runs',
    'scene_executed': 'Scene Activated successfully!',
    'scene_executing': 'Activating scene...',
    'scene_execution_failed': 'Failed to activate scene',
    'ready_device_setup': 'Ready Device Setup',
    'device_activation_code': 'Device Activation Code',
    'device_activation_code_desc': 'If you purchased a pre-configured device or obtained a setup code from the administrator, enter it here to automatically copy all control widgets and connection settings to your account.',
    'setup_code_label': 'Setup Code (CX-XXXXXX)',
    'setup_code_help': 'Enter the 9-character activation code provided with your device.',
    'admin_generate_device': 'Configure Pre-made Devices',
    'admin_generate_device_desc': 'Create, pre-configure, and manage device activation codes (widgets/settings) for your customers.',
    // Auth validations and extras
    'enter_email': 'Please enter your email',
    'enter_valid_email': 'Please enter a valid email address',
    'enter_password': 'Please enter your password',
    'password_too_short': 'Password must be at least 6 characters',
    'invalid_2fa': 'Invalid 2FA code',
    'invalid_code': 'Invalid verification code',
    'code_resent': 'Verification code resent successfully',
    'resend_code': 'Resend Code',
    'request_reset_failed': 'Failed to request reset.',
  };

  static final Map<String, String> _ar = {
    'login_title': 'ControlEx',
    'login_subtitle': 'سجل الدخول للمتابعة',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'forgot_password': 'نسيت كلمة المرور؟',
    'login_btn': 'تسجيل الدخول',
    'google_btn': 'تسجيل بجوجل',
    'no_account': 'ليس لديك حساب؟ إنشاء حساب',
    'dashboard': 'لوحة التحكم',
    'create_widgets': 'إعدادات الأدوات',
    'account': 'الحساب الشخصي',
    'no_widgets': 'لا توجد أدوات، أضف بعض الأدوات الآن!',
    'account_preferences': 'الحساب والإعدادات',
    'personal_info': 'المعلومات الشخصية',
    'username': 'اسم المستخدم',
    'new_password_optional': 'كلمة مرور جديدة (اختياري)',
    'update_profile': 'تحديث الحساب',
    'app_preferences': 'إعدادات التطبيق',
    'language': 'Language / اللغة',
    'english_ar': 'English / عربي',
    'email_notifications': 'إشعارات البريد',
    'email_desc': 'تلقي التحديثات المهمة على بريدك',
    'security_alerts': 'تنبيهات الأمان',
    'security_desc': 'إشعارك عند حدوث عمليات تسجيل دخول جديدة',
    'security_settings': 'إعدادات الأمان',
    'two_factor_auth': 'المصادقة الثنائية (2FA)',
    'enabled': 'مفعل',
    'disabled': 'مُعطل',
    'active_sessions': 'الأجهزة المتصلة',
    'data_management': 'إدارة البيانات',
    'export_config': 'تصدير بيانات وأدوات الحساب',
    'import_config': 'استيراد بيانات وأدوات',
    'clear_data': 'مسح جميع الأدوات',
    'delete_account': 'حذف الحساب نهائياً',
    'logout': 'تسجيل الخروج',
    'terminal': 'موجه الأوامر',
    'terminal_hint': 'أدخل الأمر هنا...',
    'send': 'إرسال',
    'status_connected': 'متصل',
    'status_disconnected': 'غير متصل',
    'layout_saved': 'تم حفظ الترتيب!',
    'toggle_failed': 'فشل إرسال الأمر',
    'google_sign_in_msg': 'تتطلب ميزة جوجل ربط مشروع Firebase.',
    'login_failed': 'فشل تسجيل الدخول',
    'network_error': 'خطأ في الاتصال، يرجى المحاولة لاحقاً',
    'login_required': 'يرجى تسجيل الدخول أولاً',
    'banned_title': 'الحساب محظور',
    'banned_msg': 'تم تقييد حسابك من قبل الإدارة. يرجى التواصل مع الدعم الفني لحل المشكلة.',
    'contact_admin': 'الدعم الفني والاستفسارات',
    'whatsapp_contact': 'تواصل عبر واتساب',
    'email_contact': 'تواصل عبر الإيميل',
    'close': 'إغلاق',
    'admin_panel': 'لوحة الإدارة',
    'admin_desc': 'إدارة المستخدمين وسجلات النظام',
    'technical_support': 'الدعم الفني والاستفسارات',
    'local_control': 'التحكم المحلي',
    'local_desc': 'التحكم بالأجهزة عبر الشبكة المحلية',
    'save_api_keys': 'حفظ المفاتيح',
    'update_failed': 'فشل التحديث',
    'profile_updated': 'تم تحديث الحساب بنجاح!',
    'api_keys_saved': 'تم حفظ المفاتيح بنجاح!',
    'data_cleared': 'تم مسح البيانات بنجاح',
    'no_ip_selected': 'لم يتم تحديد IP',
    'add_ip_hint': 'اضغط على الإعدادات لإضافة IP والأدوات',
    'add_widget': 'إضافة أداة',
    'error_sending_value': 'خطأ في إرسال القيمة',
    'server_waking_up': 'السيرفر بيصحى... (%s/%s)',
    'free_hosting_hint': 'الاستضافة المجانية تحتاج وقتاً للاستيقاظ 😅',
    'server_error_retry': 'تعذر الاتصال بالسيرفر. اسحب للأسفل للمحاولة مجدداً.',
    'retry': 'إعادة المحاولة',
    'notifications': 'التنبيهات',
    'no_notifications': 'لا توجد تنبيهات بعد',
    'wait_sec': 'انتظر %s ثواني',
    'users': 'المستخدمين',
    'logs': 'السجلات',
    'quota': 'الكوتة',
    'banned_users': 'المحظورين',
    'no_users': 'لا يوجد مستخدمين',
    'active': 'نشط',
    'suspended': 'معلق',
    'super_admin': 'المشرف الرئيسي',
    'widgets': 'أدوات',
    'suspend': 'تعليق',
    'activate': 'تفعيل',
    'sessions': 'الجلسات',
    'user': 'مستخدم',
    'admin': 'مسؤول',
    'system_logs': 'سجلات النظام',
    'client_errors': 'أخطاء العميل',
    'no_logs': 'لا توجد سجلات',
    'broadcast_notif': 'بث إشعار',
    'broadcast_desc': 'أرسل إشعاراً فورياً لجميع المستخدمين أو مستخدم محدد',
    'target': 'الهدف',
    'all_users': 'جميع المستخدمين',
    'notif_title_hint': 'عنوان الإشعار',
    'notif_body_hint': 'محتوى الإشعار...',
    'send_notif': 'إرسال الإشعار',
    'adafruit_quota': 'حصة Adafruit IO',
    'remaining': 'المتبقي',
    'no_banned_devices': 'لا يوجد أجهزة محظورة حالياً',
    'unknown_device': 'جهاز غير معروف',
    'at_date': 'بتاريخ',
    'unban': 'فك الحظر',
    'notif_sent': 'تم إرسال الإشعار بنجاح!',
    'error_loading_data': 'خطأ في تحميل البيانات',
    'no_quota_data': 'لا توجد بيانات حصة متاحة حالياً',
    'system_errors': 'أخطاء النظام',
    'create_widget': 'إنشاء أداة',
    'edit_widget': 'تعديل الأداة',
    'widget_details': 'تفاصيل الأداة',
    'widget_name': 'اسم الأداة',
    'feed_name': 'مسار البيانات / اسم الـ Feed',
    'firebase_db_url': 'رابط قاعدة بيانات Firebase',
    'firebase_secret': 'الرمز السري Firebase Secret',
    'provider': 'مزود الخدمة',
    'data_path': 'مسار البيانات',
    'provider_adafruit': 'Adafruit IO (للمبتدئين)',
    'provider_firebase': 'Firebase RTDB (للاحترافيين)',
    'widget_type': 'نوع الأداة',
    'commands': 'الأوامر',
    'on_command': 'أمر التشغيل (ON)',
    'off_command': 'أمر الإيقاف (OFF)',
    'configuration': 'الإعدادات',
    'unit_hint': 'الوحدة (مثال: °C, %)',
    'min_value': 'أقل قيمة',
    'max_value': 'أعلى قيمة',
    'primary_color': 'اللون الأساسي',
    'existing_widgets': 'الأدوات الموجودة حالياً',
    'no_widgets_yet': 'لم يتم بناء أي أدوات بعد.',
    'widget_created': 'تم إنشاء الأداة بنجاح!',
    'widget_updated': 'تم تحديث الأداة بنجاح!',
    'widget_deleted': 'تم حذف الأداة!',
    'device_ip': 'عنوان IP الجهاز',
    'ip_address': 'IP Address (e.g. 192.168.1.100)',
    'save': 'حفظ',
    'checking_connection': 'جاري فحص الاتصال...',
    'device_connected': 'الجهاز متصل ✓',
    'device_disconnected': 'الجهاز غير متصل',
    'command_path': 'مسار الأمر',
    'ip_saved': 'تم حفظ عنوان IP: ',
    // ترجمة جولة التطبيق التعريفية
    'tour_welcome_title': 'أهلاً بك في ControlEx! 🚀',
    'tour_welcome_desc': 'خد لفة سريعة في دقيقة واحدة تكتشف فيها ميزات التطبيق وازاي تتحكم في أجهزتك بكل سهولة!',
    'tour_drawer_title': 'القائمة الجانبية للتنقل ☰',
    'tour_drawer_desc': 'من هنا تقدر تدخل على حسابك الشخصي، إعدادات إضافة الأدوات، تغيير لغة التطبيق، ولوحة التحكم بالإدارة.',
    'tour_grid_title': 'لوحة التحكم التفاعلية 📱',
    'tour_grid_desc': 'ده مركز التحكم الذكي بتاعك! هنا هتعرض بيانات الحساسات، وتشغل المفاتيح، وتتحكم بالإنزلاق (Sliders)، وتستخدم الجويستيك وموجه الأوامر.',
    'tour_notifications_title': 'التنبيهات والإشعارات 🔔',
    'tour_notifications_desc': 'هنا بتظهر الإنذارات الفورية، تنبيهات تخطي قيم الحساسات، وإشعارات النظام عشان تفضل متابع في نفس اللحظة.',
    'tour_edit_title': 'تصميم وترتيب الواجهة 🎨',
    'tour_edit_desc': 'اضغط هنا للدخول في وضع التعديل. تقدر تسحب الأدوات وتغير حجمها عشان تصمم الواجهة بالشكل اللي تحبه ويريحك!',
    'tour_mic_title': 'التحكم الصوتي الذكي 🎙️',
    'tour_mic_desc': 'كلم بيتك الذكي! اضغط على زر المايك وقول أوامر زي "شغل النور" أو "افتح البوابة" وهيتنفذ فوراً بصوتك.',
    'tour_add_title': 'إضافة أدوات جديدة ➕',
    'tour_add_desc': 'اضغط هنا عشان تنشئ أدوات تحكم جديدة متصلة بحساب Adafruit IO بتاعك أو بأجهزتك على الشبكة المحلية في ثواني!',
    'tour_end_title': 'جاهز للانطلاق! 🎉',
    'tour_end_desc': 'دلوقتي أنت جاهز للتحكم الكامل! ابدأ صمم لوحة التحكم الخاصة بأجهزتك الذكية واستمتع بالتجربة.',
    'tour_next': 'التالي',
    'tour_back': 'السابق',
    'tour_skip': 'تخطي',
    'tour_finish': 'إنهاء',
    'tour_start': 'بدء الجولة',
    'tour_interact_hint': 'يرجى الضغط على المنطقة المحددة للمتابعة.',
    'tour_tap_to_continue': 'اضغط للمتابعة',
    // Multi-page additions
    'tour_settings_transition_title': 'إعدادات الأدوات ⚙️',
    'tour_settings_transition_desc': 'دعنا ننتقل إلى شاشة إعدادات الأدوات لنرى كيف نصمم ونربط الأزرار بالمجاري الحقيقية!',
    'tour_settings_name_title': 'اسم الأداة',
    'tour_settings_name_desc': 'أدخل اسماً واضحاً للأداة (مثل إضاءة الصالة). اكتبه ثم اضغط التالي.',
    'tour_settings_feed_title': 'مجرى البيانات (Feed)',
    'tour_settings_feed_desc': 'أدخل اسم مجرى البيانات أو اختره من مزود الخدمة لربط الأداة بجهازك.',
    'tour_settings_type_title': 'نوع الأداة',
    'tour_settings_type_desc': 'اختر نوع التحكم. هل هو زر تشغيل، شريط تمرير، أم حساس؟ اختر ثم اضغط التالي.',
    'tour_settings_save_title': 'حفظ وإنشاء الأداة 💾',
    'tour_settings_save_desc': 'عند اكتمال البيانات، اضغط هنا لإنشاء الزر وضمه للشاشة. دعنا ننتقل الآن لاستكشاف التحكم المحلي بدون إنترنت!',
    'tour_local_grid_title': 'التحكم المحلي دون إنترنت 📶',
    'tour_local_grid_desc': 'هنا تتحكم في أجهزتك المحلية مباشرة عبر الواي فاي، بسرعة فائقة وبشكل كامل أوفلاين دون إنترنت! دعنا ننتقل الآن للحساب والتفضيلات.',
    'tour_account_lang_title': 'تفضيلات التطبيق ⚙️',
    'tour_account_lang_desc': 'تغيير لغة التطبيق بالكامل وبشكل فوري بين العربية والإنجليزية، أو الانتقال للتحكم المحلي من هنا.',
    'tour_account_support_title': 'الدعم الفني المباشر 📞',
    'tour_account_support_desc': 'هل تحتاج لمساعدة؟ تواصل مع المطورين مباشرة عبر الإيميل أو الواتساب بضغطة واحدة!',
    // Sandbox Guided Practice
    'sandbox_title': 'التدريب العملي 🎯',
    'sandbox_step1': 'مرحباً بك في مساحة التدريب! اضغط على زر + لإنشاء أداتك الأولى الوهمية.',
    'sandbox_step2': 'ممتاز! أدخل اسم الأداة واضغط حفظ.',
    'sandbox_step3': 'رائع، ظهرت الأداة! الآن اضغط على زر التعديل ✏️ بالأعلى لنتمكن من التحكم بحجمها ومكانها.',
    'sandbox_step4': 'تستطيع الآن سحب الأداة لتحريكها، أو سحب الزاوية السفلية لتكبيرها. جرب ذلك الآن!',
    'sandbox_success': 'أحسنت! 🎉 لقد أتممت التدريب بنجاح وأنت الآن جاهز لاستخدام التطبيق.',
    'sandbox_finish_btn': 'ابدأ الآن',
    // شاشة الأتمتة
    'automations': 'الأتمتة',
    'automations_subtitle': 'أنشئ قواعد ذكية IF/THEN',
    'create_rule': 'إنشاء قاعدة',
    'edit_rule': 'تعديل القاعدة',
    'if_trigger': 'إذا',
    'then_action': 'نفّذ',
    'select_sensor': 'اختر الحساس',
    'select_widget': 'اختر الأداة',
    'select_condition': 'اختر الشرط',
    'enter_value': 'أدخل القيمة',
    'greater_than': 'أكبر من (>)',
    'less_than': 'أقل من (<)',
    'equal_to': 'يساوي (=)',
    'not_equal': 'لا يساوي (≠)',
    'action_turn_on': 'تشغيل أداة',
    'action_turn_off': 'إيقاف أداة',
    'action_send_notif': 'إرسال إشعار',
    'action_send_email': 'إرسال بريد تنبيه',
    'action_send_feed': 'إرسال قيمة للفيد',
    'select_action': 'اختر الإجراء',
    'rule_name': 'اسم القاعدة',
    'rule_name_hint': 'مثال: إضاءة ليلية تلقائية',
    'scenario_running': 'تعمل',
    'scenario_stopped': 'متوقفة',
    'no_rules': 'لا توجد قواعد أتمتة بعد',
    'no_rules_hint': 'اضغط + لإنشاء أول قاعدة ذكية!',
    'rule_created': 'تم إنشاء القاعدة!',
    'rule_updated': 'تم تحديث القاعدة!',
    'rule_deleted': 'تم حذف القاعدة!',
    'delete_rule_confirm': 'هل تريد حذف هذه القاعدة؟',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'save_rule': 'حفظ القاعدة',
    'notif_message': 'رسالة الإشعار',
    'notif_message_hint': 'مثال: درجة الحرارة مرتفعة جداً!',
    'email_address': 'البريد الإلكتروني',
    'feed_value': 'القيمة المُرسلة',
    'my_scenarios': 'السيناريوهات',
    // Power Saving
    'power_saving': 'توفير الطاقة',
    'power_saving_desc': 'تقليل الحمل على السيرفر بتقليل معدل الاستعلام',
    'power_saving_on': 'توفير الطاقة مفعل — استعلام كل ~60 ثانية',
    'power_saving_off': 'توفير الطاقة معطل — استعلام كل ~10 ثوانٍ',
    'power_saving_enabled': 'تم تفعيل توفير الطاقة ⚡',
    'power_saving_disabled': 'تم إلغاء توفير الطاقة',
    // Admin Automations
    'admin_automations': 'الأتمتة وتوفير الطاقة',
    'admin_automations_subtitle': 'مراقبة أتمتة المستخدمين وإدارة توفير الطاقة لكل مستخدم.',
    'admin_automations_subtitle_ar': 'مراقبة أتمتة المستخدمين وإدارة توفير الطاقة لكل مستخدم.',
    'total_automations': 'إجمالي الأتمتة',
    'active_automations': 'نشطة',
    'inactive_automations': 'متوقفة',
    'no_automations': 'لا توجد أتمتة',
    'power_saving_mode': 'توفير الطاقة',
    // Power saving reminder
    'power_saving_reminder_title': 'وضع توفير الطاقة ⚡',
    'power_saving_reminder_msg': 'إذا كنت لا تحتاج تحديثات فورية، رجاءً شغّل وضع توفير الطاقة للحفاظ على استقرار النظام وتقليل الحمل على السيرفر.',
    'enable_now': 'تشغيل الآن',
    'later': 'لاحقاً',
    // Smart Scenes / Macros
    'smart_scenes': 'السيناريوهات الذكية',
    'smart_scenes_subtitle': 'تشغيل مجموعة أوامر بضغطة واحدة',
    'quick_scenes': 'السيناريوهات السريعة',
    'create_scene': 'إنشاء سيناريو',
    'edit_scene': 'تعديل السيناريو',
    'delete_scene': 'حذف السيناريو',
    'scene_name': 'اسم السيناريو',
    'scene_name_hint': 'مثال: وضع السينما، وضع النوم',
    'scene_icon': 'أيقونة السيناريو',
    'scene_color': 'لون السمة',
    'show_on_dashboard': 'عرض في لوحة التحكم',
    'no_scenes': 'لا توجد سيناريوهات ذكية بعد',
    'no_scenes_hint': 'اضغط + لإنشاء أول سيناريو ذكي!',
    'scene_created': 'تم إنشاء السيناريو الذكي بنجاح!',
    'scene_updated': 'تم تحديث السيناريو بنجاح!',
    'scene_deleted': 'تم حذف السيناريو الذكي!',
    'select_devices': 'اختر الأجهزة والأوامر',
    'select_devices_desc': 'حدد الأدوات وقيم الأوامر التي سيتم إرسالها عند تشغيل السيناريو',
    'scene_executed': 'تم تفعيل السيناريو بنجاح!',
    'scene_executing': 'جاري تفعيل السيناريو...',
    'scene_execution_failed': 'فشل تفعيل بعض أوامر السيناريو',
    'ready_device_setup': 'إعداد جهاز جاهز',
    'device_activation_code': 'كود تفعيل وإعداد الجهاز',
    'device_activation_code_desc': 'إذا قمت بشراء جهاز مهيأ مسبقاً أو حصلت على كود إعداد من المسؤول، أدخله هنا لنسخ جميع أدوات التحكم وإعدادات الاتصال إلى حسابك تلقائياً.',
    'setup_code_label': 'كود التفعيل (Setup Code)',
    'setup_code_help': 'أدخل الكود المكون من بادئة CX- متبوعة بـ 6 رموز.',
    'admin_generate_device': 'إعداد وتجهيز الأجهزة الجاهزة',
    'admin_generate_device_desc': 'إنشاء وتجهيز أكواد إعداد وتفعيل الأجهزة مسبقاً للعملاء مع أدوات التحكم والإعدادات.',
    // Auth validations and extras
    'enter_email': 'يرجى إدخال البريد الإلكتروني',
    'enter_valid_email': 'يرجى إدخال بريد إلكتروني صحيح',
    'enter_password': 'يرجى إدخال كلمة المرور',
    'password_too_short': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
    'invalid_2fa': 'رمز التحقق الثنائي غير صحيح',
    'invalid_code': 'رمز التحقق غير صحيح',
    'code_resent': 'تم إعادة إرسال رمز التحقق بنجاح',
    'resend_code': 'إعادة إرسال الرمز',
    'request_reset_failed': 'فشل طلب إعادة التعيين.',
  };
}
